import { signal } from '@angular/core';
import { DrawerDirection, DrawerDirectionType } from '../../types';

export const createDrawerStateMock = () => ({
  stateChange: signal<void>(undefined),
  isOpen: signal<boolean>(false),
  isDragging: signal<boolean>(false),
  drawerRef: signal<HTMLDivElement | null>(null),
  overlayRef: signal<HTMLElement | null>(null),
  direction: signal<DrawerDirectionType>(DrawerDirection.BOTTOM),
  hasBeenOpened: signal<boolean>(false),
  openTime: signal<Date | null>(null),
  shouldScaleBackground: signal<boolean>(false),
  backgroundColorOnScale: signal<boolean>(false),
  noBodyStyles: signal<boolean>(false),
  nested: signal<boolean>(false),
  modal: signal<boolean>(false),
  preventScrollRestoration: signal<boolean>(false),

  setIsOpen: (isOpen: boolean) => {},
  setIsDragging: (isDragging: boolean) => {},
  setDirection: (direction: DrawerDirectionType) => {},
  setDrawerRef: (ref: HTMLDivElement | null) => {},
  setOverlayRef: (ref: HTMLElement | null) => {},
  setScaleBackground: (value: boolean) => {},
  setBackgroundColor: (value: boolean) => {},
  setNoBodyStyles: (value: boolean) => {},
  setNested: (value: boolean) => {},
  setModal: (value: boolean) => {},
  setHasBeenOpened: (value: boolean) => {},
  setPreventScrollRestoration: (value: boolean) => {},
  setOpenTime: (date: Date | null) => {},
  getShouldScaleBackground: () => false,
  getBackgroundColorOnScale: () => false,
  getNoBodyStyles: () => false,
  getNested: () => false,
  getModal: () => false,
  getHasBeenOpened: () => false,
  getPreventScrollRestoration: () => false,
  ngOnDestroy: () => {},
});
